const types = {
  //ui
  TOGGLE_MODAL: 'TOGGLE_MODAL',

  //auth
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',

  UPDATE_USERS_ONLINE:'UPDATE_USERS_ONLINE',

  RECEIVE_TYPING:'RECEIVE_TYPING',
  //messages
  LOAD_MESSAGES:'LOAD_MESSAGES',

  FETCH_MESSAGES_REQUEST: 'FETCH_MESSAGES_REQUEST',
  FETCH_MESSAGES_SUCCESS: 'FETCH_MESSAGES_SUCCESS',
  FETCH_MESSAGES_FAILURE: 'FETCH_MESSAGES_FAILURE',

  DELETE_MESSAGE_REQUEST: 'DELETE_MESSAGE_REQUEST',
  DELETE_MESSAGE_SUCCESS: 'DELETE_MESSAGE_SUCCESS',
  DELETE_MESSAGE_FAILURE: 'DELETE_MESSAGE_FAILURE',
  DELETE_MESSAGE: 'DELETE_MESSAGE',

  EDIT_MESSAGE_REQUEST: 'EDIT_MESSAGE_REQUEST',
  EDIT_MESSAGE_SUCCESS: 'EDIT_MESSAGE_SUCCESS',
  EDIT_MESSAGE_FAILURE: 'EDIT_MESSAGE_FAILURE',
  UPDATE_MESSAGE:'UPDATE_MESSAGE',
  //channels
  FETCH_CHANNELS_REQUEST: 'FETCH_CHANNELS_REQUEST',
  FETCH_CHANNELS_SUCCESS: 'FETCH_CHANNELS_SUCCESS',
  FETCH_CHANNELS_FAILURE: 'FETCH_CHANNELS_FAILURE',

  CREATE_CHANNEL_REQUEST: 'CREATE_CHANNEL_REQUEST',
  CREATE_CHANNEL_SUCCESS: 'CREATE_CHANNEL_SUCCESS',
  CREATE_CHANNEL_FAILURE: 'CREATE_CHANNEL_FAILURE',

  EDIT_CHANNEL_REQUEST: 'EDIT_CHANNEL_REQUEST',
  EDIT_CHANNEL_SUCCESS: 'EDIT_CHANNEL_SUCCESS',
  EDIT_CHANNEL_FAILURE: 'EDIT_CHANNEL_FAILURE',

  DELETE_CHANNEL_REQUEST: 'DELETE_CHANNEL_REQUEST',
  DELETE_CHANNEL_SUCCESS: 'DELETE_CHANNEL_SUCCESS',
  DELETE_CHANNEL_FAILURE: 'DELETE_CHANNEL_FAILURE',

  EDIT_CHANNELS_ORDER_REQUEST: 'EDIT_CHANNELS_ORDER_REQUEST',
  EDIT_CHANNELS_ORDER_SUCCESS: 'EDIT_CHANNELS_ORDER_SUCCESS',
  EDIT_CHANNELS_ORDER_FAILURE: 'EDIT_CHANNELS_ORDER_FAILURE',


  SEND_TYPING_REQUEST: 'SEND_TYPING_REQUEST',
  SEND_TYPING_SUCCESS: 'SEND_TYPING_SUCCESS',
  SEND_TYPING_FAILURE: 'SEND_TYPING_FAILURE',
  START_TYPING:'START_TYPING',
  STOP_TYPING:'STOP_TYPING',

  //user
  EDIT_USER_REQUEST: 'EDIT_USER_REQUEST',
  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
  EDIT_USER_FAILURE: 'EDIT_USER_FAILURE',

  UPLOAD_USER_AVATAR_REQUEST: 'UPLOAD_USER_AVATAR_REQUEST',
  UPLOAD_USER_AVATAR_SUCCESS: 'UPLOAD_USER_AVATAR_SUCCESS',
  UPLOAD_USER_AVATAR_FAILURE: 'UPLOAD_USER_AVATAR_FAILURE',

  FETCH_CURRENT_USER_REQUEST: 'FETCH_CURRENT_USER_REQUEST',
  FETCH_CURRENT_USER_SUCCESS: 'FETCH_CURRENT_USER_SUCCESS',
  FETCH_CURRENT_USER_FAILURE: 'FETCH_CURRENT_USER_FAILURE',

  CREATE_MESSAGE_REQUEST: 'CREATE_MESSAGE_REQUEST',
  CREATE_MESSAGE_SUCCESS: 'CREATE_MESSAGE_SUCCESS',
  CREATE_MESSAGE_FAILURE: 'CREATE_MESSAGE_FAILURE',
  RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',

  SAVE_SCROLL_POSITION:'SAVE_SCROLL_POSITION',
  SAVE_LAST_VISIBLE_MESSAGE: 'SAVE_LAST_VISIBLE_MESSAGE',
  SET_CHANNEL_HAS_NEW_MESSAGES: 'SET_CHANNEL_HAS_NEW_MESSAGES',
  UNSET_CHANNEL_HAS_NEW_MESSAGES: 'UNSET_CHANNEL_HAS_NEW_MESSAGES',
  SELECT_CHANNEL: 'SELECT_CHANNEL',

  SET_EDITABLE_MESSAGE: 'SET_EDITABLE_MESSAGE',
  UNSET_EDITABLE_MESSAGE: 'UNSET_EDITABLE_MESSAGE',

  //servers
  CREATE_SERVER_REQUEST: 'CREATE_SERVER_REQUEST',
  CREATE_SERVER_SUCCESS: 'CREATE_SERVER_SUCCESS',
  CREATE_SERVER_FAILURE: 'CREATE_SERVER_FAILURE',

  FETCH_SERVERS_REQUEST: 'FETCH_SERVERS_REQUEST',
  FETCH_SERVERS_SUCCESS: 'FETCH_SERVERS_SUCCESS',
  FETCH_SERVERS_FAILURE: 'FETCH_SERVERS_FAILURE',
  SELECT_SERVER: 'SELECT_SERVER',

  EDIT_SERVERS_ORDER_REQUEST: 'EDIT_SERVERS_ORDER_REQUEST',
  EDIT_SERVERS_ORDER_SUCCESS: 'EDIT_SERVERS_ORDER_SUCCESS',
  EDIT_SERVERS_ORDER_FAILURE: 'EDIT_SERVERS_ORDER_FAILURE',

  UPLOAD_SERVER_ICON_REQUEST: 'UPLOAD_SERVER_ICON_REQUEST',
  UPLOAD_SERVER_ICON_SUCCESS: 'UPLOAD_SERVER_ICON_SUCCESS',
  UPLOAD_SERVER_ICON_FAILURE: 'UPLOAD_SERVER_ICON_FAILURE',

  //roles
  FETCH_ROLES_REQUEST: 'FETCH_ROLES_REQUEST',
  FETCH_ROLES_SUCCESS: 'FETCH_ROLES_SUCCESS',
  FETCH_ROLES_FAILURE: 'FETCH_ROLES_FAILURE',

  CREATE_ROLE_REQUEST: 'CREATE_ROLE_REQUEST',
  CREATE_ROLE_SUCCESS: 'CREATE_ROLE_SUCCESS',
  CREATE_ROLE_FAILURE: 'CREATE_ROLE_FAILURE',

  DELETE_ROLE_REQUEST: 'DELETE_ROLE_REQUEST',
  DELETE_ROLE_SUCCESS: 'DELETE_ROLE_SUCCESS',
  DELETE_ROLE_FAILURE: 'DELETE_ROLE_FAILURE',

  EDIT_ROLE_REQUEST: 'EDIT_ROLE_REQUEST',
  EDIT_ROLE_SUCCESS: 'EDIT_ROLE_SUCCESS',
  EDIT_ROLE_FAILURE: 'EDIT_ROLE_FAILURE',

  SELECT_ROLE:'SELECT_ROLE',

  EDIT_ROLES_ORDER_REQUEST: 'EDIT_ROLES_ORDER_REQUEST',
  EDIT_ROLES_ORDER_SUCCESS: 'EDIT_ROLES_ORDER_SUCCESS',
  EDIT_ROLES_ORDER_FAILURE: 'EDIT_ROLES_ORDER_FAILURE',

  //permissions
  FETCH_PERMISSIONS_REQUEST: 'FETCH_PERMISSIONS_REQUEST',
  FETCH_PERMISSIONS_SUCCESS: 'FETCH_PERMISSIONS_SUCCESS',
  FETCH_PERMISSIONS_FAILURE: 'FETCH_PERMISSIONS_FAILURE',

};

export default types;
