const types = [

  //ui
  'TOGGLE_MODAL',
  'CHANGE_PARAMS',
  'WINDOW_BLUR',
  'OPEN_CONFIRM',
  'CONFIRM_YES',
  'CONFIRM_NO',

  'SET_EDITABLE_MESSAGE',
  'UNSET_EDITABLE_MESSAGE',

  'UPDATE_USERS_ONLINE',

  //channelsData
  'LEAVE_CHANNEL',
  'OPEN_CHANNEL',

  'SWITCH_CHANNEL',

  'SET_CHANNEL_HAS_NEW_MESSAGES',
  'UNSET_CHANNEL_HAS_NEW_MESSAGES',

  //channels

  'FETCH_CHANNELS_REQUEST',
  'FETCH_CHANNELS_SUCCESS',
  'FETCH_CHANNELS_FAILURE',

  'CREATE_CHANNEL_REQUEST',
  'CREATE_CHANNEL_SUCCESS',
  'CREATE_CHANNEL_FAILURE',

  'EDIT_CHANNEL_REQUEST',
  'EDIT_CHANNEL_SUCCESS',
  'EDIT_CHANNEL_FAILURE',

  'DELETE_CHANNEL_REQUEST',
  'DELETE_CHANNEL_SUCCESS',
  'DELETE_CHANNEL_FAILURE',

  'EDIT_CHANNELS_ORDER_REQUEST',
  'EDIT_CHANNELS_ORDER_SUCCESS',
  'EDIT_CHANNELS_ORDER_FAILURE',

  //typing
  'SEND_TYPING_REQUEST',
  'SEND_TYPING_SUCCESS',
  'SEND_TYPING_FAILURE',
  'START_TYPING',
  'STOP_TYPING',

  //auth
  'LOGIN_REQUEST',
  'LOGIN_SUCCESS',
  'LOGIN_FAILURE',

  'SIGNUP_REQUEST',
  'SIGNUP_SUCCESS',
  'SIGNUP_FAILURE',

  'LOGOUT_REQUEST',
  'LOGOUT_SUCCESS',
  'LOGOUT_FAILURE',

  //messages
  'CREATE_MESSAGE_REQUEST',
  'CREATE_MESSAGE_SUCCESS',
  'CREATE_MESSAGE_FAILURE',
  'RECEIVE_MESSAGE',

  'LOAD_CACHE_BEFORE',
  'LOAD_CACHE_AFTER',
//ACK
  'FETCH_MESSAGES_ACK_REQUEST',
  'FETCH_MESSAGES_ACK_SUCCESS',
  'FETCH_MESSAGES_ACK_FAILURE',

  'UPDATE_MESSAGE_ACK_REQUEST',
  'UPDATE_MESSAGE_ACK_SUCCESS',
  'UPDATE_MESSAGE_ACK_FAILURE',

  'FETCH_MESSAGES_REQUEST',
  'FETCH_MESSAGES_SUCCESS',
  'FETCH_MESSAGES_FAILURE',

  'DELETE_MESSAGE_REQUEST',
  'DELETE_MESSAGE_SUCCESS',
  'DELETE_MESSAGE_FAILURE',

  'EDIT_MESSAGE_REQUEST',
  'EDIT_MESSAGE_SUCCESS',
  'EDIT_MESSAGE_FAILURE',
  'UPDATE_MESSAGE',

  //user
  'EDIT_USER_REQUEST',
  'EDIT_USER_SUCCESS',
  'EDIT_USER_FAILURE',

  'UPLOAD_USER_AVATAR_REQUEST',
  'UPLOAD_USER_AVATAR_SUCCESS',
  'UPLOAD_USER_AVATAR_FAILURE',

  'FETCH_CURRENT_USER_REQUEST',
  'FETCH_CURRENT_USER_SUCCESS',
  'FETCH_CURRENT_USER_FAILURE',

  //servers
  'CREATE_SERVER_REQUEST',
  'CREATE_SERVER_SUCCESS',
  'CREATE_SERVER_FAILURE',

  'FETCH_SERVERS_REQUEST',
  'FETCH_SERVERS_SUCCESS',
  'FETCH_SERVERS_FAILURE',
  'SELECT_SERVER',

  'EDIT_SERVERS_ORDER_REQUEST',
  'EDIT_SERVERS_ORDER_SUCCESS',
  'EDIT_SERVERS_ORDER_FAILURE',

  'UPLOAD_SERVER_ICON_REQUEST',
  'UPLOAD_SERVER_ICON_SUCCESS',
  'UPLOAD_SERVER_ICON_FAILURE',

  //roles
  'FETCH_ROLES_REQUEST',
  'FETCH_ROLES_SUCCESS',
  'FETCH_ROLES_FAILURE',

  'CREATE_ROLE_REQUEST',
  'CREATE_ROLE_SUCCESS',
  'CREATE_ROLE_FAILURE',

  'DELETE_ROLE_REQUEST',
  'DELETE_ROLE_SUCCESS',
  'DELETE_ROLE_FAILURE',

  'EDIT_ROLE_REQUEST',
  'EDIT_ROLE_SUCCESS',
  'EDIT_ROLE_FAILURE',

  'SELECT_ROLE',
  'EDIT_ROLES_ORDER_REQUEST',
  'EDIT_ROLES_ORDER_SUCCESS',
  'EDIT_ROLES_ORDER_FAILURE',

  //permissions
  'FETCH_PERMISSIONS_REQUEST',
  'FETCH_PERMISSIONS_SUCCESS',
  'FETCH_PERMISSIONS_FAILURE',


  //scroll
  'SET_SCROLL_POSITION',
];


function createTypes(arrayOfTypes){
  const types={};
  arrayOfTypes.forEach(t=>types[t]=t);
  return types;
}
export default createTypes(types);
